name: E2E

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - 'solutions/**'
      - 'assets/**'
      - 'troubleshooting/**'
      - ".github/ISSUE_TEMPLATE/*"
    branches:
      - main
      - release-*

env:
  GO_VERSION: '1.22'
  GO_REQUIRED_MIN_VERSION: ''
  USE_EXISTING_CLUSTER: false # set to true to use an existing kind cluster for debugging with act

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: add permisson to docker.sock
        run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }} # this step only runs locally when using the https://github.com/nektos/act to debug the e2e
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.22.0
          skipClusterCreation: ${{ env.USE_EXISTING_CLUSTER }}
      - name: Set KUBECONFIG
        run: |
          mkdir -p /home/runner/.kube
          kind get kubeconfig > /home/runner/.kube/config
        if: ${{ env.USE_EXISTING_CLUSTER }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: Build images
        run: IMAGE_TAG=e2e make images
      - name: Load images
        run: |
          kind load docker-image --name=kind quay.io/open-cluster-management/registration-operator:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/registration:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/work:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/placement:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/addon-manager:e2e
      - name: Test E2E
        run: |
          IMAGE_TAG=e2e make test-e2e
        env:
          KUBECONFIG: /home/runner/.kube/config
  e2e-hosted:
    runs-on: ubuntu-latest
    steps:
      - name: add permisson to docker.sock
        run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }} # this step only runs locally when using the https://github.com/nektos/act to debug the e2e
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.22.0
          skipClusterCreation: ${{ env.USE_EXISTING_CLUSTER }}
      - name: Set KUBECONFIG
        run: |
          mkdir -p /home/runner/.kube
          kind get kubeconfig > /home/runner/.kube/config
        if: ${{ env.USE_EXISTING_CLUSTER }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: Build images
        run: IMAGE_TAG=e2e make images
      - name: Load images
        run: |
          kind load docker-image --name=kind quay.io/open-cluster-management/registration-operator:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/registration:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/work:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/placement:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/addon-manager:e2e
      - name: Test E2E
        run: |
          IMAGE_TAG=e2e KLUSTERLET_DEPLOY_MODE=SingletonHosted make test-e2e
        env:
          KUBECONFIG: /home/runner/.kube/config
  e2e-singleton:
    runs-on: ubuntu-latest
    steps:
      - name: add permisson to docker.sock
        run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }} # this step only runs locally when using the https://github.com/nektos/act to debug the e2e
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.22.0
          skipClusterCreation: ${{ env.USE_EXISTING_CLUSTER }}
      - name: Set KUBECONFIG
        run: |
          mkdir -p /home/runner/.kube
          kind get kubeconfig > /home/runner/.kube/config
        if: ${{ env.USE_EXISTING_CLUSTER }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: Build images
        run: IMAGE_TAG=e2e make images
      - name: Load images
        run: |
          kind load docker-image --name=kind quay.io/open-cluster-management/registration-operator:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/registration:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/work:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/placement:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/addon-manager:e2e
      - name: Test E2E
        run: |
          IMAGE_TAG=e2e KLUSTERLET_DEPLOY_MODE=Singleton make test-e2e
        env:
          KUBECONFIG: /home/runner/.kube/config
  e2e-multiplehubs:
    runs-on: ubuntu-latest
    steps:
      - name: add permisson to docker.sock
        run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }} # this step only runs locally when using the
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: Build images
        run: IMAGE_TAG=e2e make images
      - name: Setup kind cluster
        uses: xuezhaojun/kind-clusters@main
        with:
          clusters: "hub1,hub2,spoke"
          images: >
            quay.io/open-cluster-management/registration-operator:e2e,
            quay.io/open-cluster-management/registration:e2e,
            quay.io/open-cluster-management/work:e2e,
            quay.io/open-cluster-management/placement:e2e,
            quay.io/open-cluster-management/addon-manager:e2e
      - name: Test E2E
        run: |
          # Note: if you're going to run e2e locally, make sure the docker resource has at least 8G memory
          # If you want to run this e2e locally, using the hack/e2e-multiplehubs-local-test.sh or leverage the nektos/act tool

          # get kubeconfig for hub1, hub2, spoke
          kind get kubeconfig --name=hub1 > /home/runner/.kube/hub1
          kind get kubeconfig --name=hub2 > /home/runner/.kube/hub2
          kind get kubeconfig --name=spoke > /home/runner/.kube/spoke

          # get bootstrap kubeconfig of hub1, hub2
          # to enable internal communication between agent and hubs, we use the flag "--internal"
          kind get kubeconfig --name=hub1 --internal > /home/runner/.kube/hub1-kubeconfig
          kind get kubeconfig --name=hub2 --internal > /home/runner/.kube/hub2-kubeconfig

          # deploy ocm hub on hub1
          make deploy-hub-operator apply-hub-cr KUBECONFIG=/home/runner/.kube/hub1 IMAGE_TAG=e2e

          # deploy ocm hub on hub2
          make deploy-hub-operator apply-hub-cr KUBECONFIG=/home/runner/.kube/hub2 IMAGE_TAG=e2e

          # deploy ocm agent on spoke
          make deploy-spoke-operator KUBECONFIG=/home/runner/.kube/spoke IMAGE_TAG=e2e

          # deploy multiple bootstrapkubeconfig secrets on the spoke cluster
          # bootstrap-secret command install the secret constantly to the namespace "open-cluster-management-agent"
          make bootstrap-secret HUB_KUBECONFIG=/home/runner/.kube/hub1-kubeconfig HUB_KUBECONFIG_SECRET_NAME=bootstraphub1 IMAGE_TAG=e2e
          make bootstrap-secret HUB_KUBECONFIG=/home/runner/.kube/hub2-kubeconfig HUB_KUBECONFIG_SECRET_NAME=bootstraphub2 IMAGE_TAG=e2e

          # run e2e
          make run-e2e-multiplehubs \
            HUB1_KUBECONFIG=/home/runner/.kube/hub1 \
            HUB2_KUBECONFIG=/home/runner/.kube/hub2 \
            SPOKE_KUBECONFIG=/home/runner/.kube/spoke \
            IMAGE_TAG=e2e
